std_msgs/Header header

uint8 cleaning_mode_status
uint8 front_spray_action
uint8 auto_cleaning_mode_status
uint8 high_voltage_status
uint8 water_tank_lid_action
uint8 sewage_discharge_action
uint8 music_status
uint8 working_lamp_status
uint8 sweeping_disc_speed_status
uint8 left_arrow_lamp_status
uint8 right_arrow_lamp_status
uint8 sewage_tank_door_opening
uint8 sewage_tank_door_closing
uint8 sewage_tank_lifting
uint8 sewage_tank_droping
uint8 sewage_tank_force_action
uint8 self_cleaning_action
uint8 sewage_tank_lifting_finished
uint8 sewage_tank_droping_finished
uint8 left_sweeping_disc_raising
uint8 left_sweeping_disc_droping
uint8 right_sweeping_disc_raising
uint8 right_sweeping_disc_droping
uint8 sucker_raising
uint8 sucker_droping
uint8 left_rotation_on
uint8 right_rotation_on
uint8 all_rotation_on
uint8 left_water_jet_on
uint8 right_water_jet_on
uint8 sucker_water_jet_on
uint8 left_spray_on
uint8 right_spray_on
uint8 sucker_spray_on
uint8 high_pressure_pump_clutch_status
uint8 water_tank_lid_closed_signal
uint8 sewage_tank_door_opened_signal
uint8 pole_down_signal
uint8 main_water_valve_status
uint8 water_low_warning
uint8 sewage_full_warning
uint8 sewage_tank_door_closed_finished
uint8 sewage_outlet_out_signal
uint8 sewage_level_percent
uint8 water_level_percent

uint16 blower_motor_speed

uint8 blower_error_level
uint8 blower_error_code1
uint8 blower_error_code2

uint8 oil_pump_error_code1
uint8 oil_pump_error_code2


uint8 ad_mode_of_bcm
uint8 power_on_switch_of_adcu
uint8 left_door_open_switch
uint8 right_door_open_switch
uint8 door_open_warning

