std_msgs/Header header

float32 de_phi_steer_angle
uint8  de_ctrl_mod_resp_overridedetection
uint8  de_ctrl_mod_resp_torque_demand

uint8 veh_da_st_src_eng_ctrl_mp
float64 veh_da_n_eng_spd_mp
int16 veh_da_prc_trq_eng_nom_fric_mp
int16 veh_da_prc_trq_estimd_loss_mp
uint8 veh_da_st_clu_swt_mp
uint8 veh_da_st_brk_swt_mp
float64 veh_da_r_accr_pedl_mp
float64 veh_da_r_tra_cur_gear_mp
int16 veh_da_st_tra_cur_gear_mp
int16 veh_da_st_tra_sel_gear_mp
uint8 veh_da_st_tra_egd_mp
uint8 veh_da_st_tra_sht_mp
float64 veh_da_v_ego_spd_mp
float64 veh_da_r_brk_pedl_mp
uint8 veh_da_st_src_brk_mp
float64 veh_da_a_ego_acc_mp
uint8 epb_park_br_k_st

uint8 xbr_ctrl_mode
uint8 ebs_brake_switch

#2025.4.8 add
uint8 ecu_adas_mode_st
uint8 ad_mode_of_vecu
uint8 epbad_mode_state_ps

