std_msgs/Header header

int16 veh_da_prc_actu_trq_mp
int16 veh_da_prc_drvr_dmd_trq_mp
float64 veh_da_n_eng_spd_mp
int16 veh_da_prc_trq_eng_nom_fric_mp
int16 veh_da_prc_trq_estimd_loss_mp
uint8 veh_da_st_clu_swt_mp
uint8 veh_da_st_brk_swt_mp
float64 veh_da_r_accr_pedl_mp
float64 veh_da_r_tra_cur_gear_mp
int16 veh_da_st_tra_cur_gear_mp
int16 veh_da_st_tra_sel_gear_mp
uint8 veh_da_st_tra_egd_mp
uint8 veh_da_st_tra_sht_mp
uint8 veh_da_st_tra_trq_lim_mp
float64 veh_da_v_ego_spd_mp
float64 veh_da_r_brk_pedl_mp
uint8 veh_da_st_src_brk_mp
float64 veh_da_a_ego_acc_mp
uint8 epb_park_br_k_st
uint8 trns_md3_mp

uint8 vtd1_veh_state
uint8 ebs_brake_switch

uint8 service_brake_circuit_1_air_pressure
uint8 service_brake_circuit_2_air_pressure
uint8 ad_mode_of_scu
