std_msgs/Header header
geometry_msgs/Pose goal_pose
autoware_planning_msgs_v49/LaneletSegment[] segments
unique_identifier_msgs/UUID uuid
bool allow_modification
---
autoware_common_msgs_v49/ResponseStatus status
